version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: coaching_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coaching_db
      MYSQL_USER: coaching_user
      MYSQL_PASSWORD: coaching_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
